plugins:
  - jekyll-feed
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /package.json
  - /package-lock.json
  - /*.config.js
  - /.vscode
  - /.nvmrc
